//random room spawner. takes random rooms from their appropriate map file and places them. the room will spawn with the spawner in the bottom left corner
// This code is taken from https://github.com/beestation
/obj/effect/spawner/room
	name = "random room spawner"
	icon = 'icons/effects/landmarks_static.dmi'
	icon_state = "random_room"
	dir = NORTH
	var/room_width = 0
	var/room_height = 0
	/// List of room IDs we want
	var/list/rooms

/obj/effect/spawner/room/Initialize(mapload)
	. = ..()
#ifdef UNIT_TESTS
	// These are far too flakey to be including in the tests
	var/list/turf/room_turfs = block(
		x, y, z,
		x + room_width - 1, y + room_height - 1, z,
	)
	for(var/turf/room_turf in room_turfs)
		room_turf.ChangeTurf(/turf/open/floor/plating, flags = CHANGETURF_IGNORE_AIR)
	return INITIALIZE_HINT_QDEL
#else
	if(!length(SSmapping.random_room_templates))
		message_admins("Room spawner created with no templates available. This shouldn't happen.")
		return INITIALIZE_HINT_QDEL

	var/list/possible_templates = list()
	for(var/datum/map_template/random_room/candidate as anything in SSmapping.random_room_templates)
		if(candidate.stock <= 0 || room_height != candidate.template_height || room_width != candidate.template_width)
			continue
		if(length(rooms) && !(candidate.room_id in rooms))
			continue
		possible_templates[candidate] = candidate.weight

	if(!length(possible_templates))
		stack_trace("Failed to find a valid random room / Room Info - height: [room_height], width: [room_width], name: [name]")
		return

	var/datum/map_template/random_room/template = pick_weight(possible_templates)
	template.stock--
	template.weight /= 2
	INVOKE_ASYNC(src, PROC_REF(place_template), template)
#endif

/obj/effect/spawner/room/proc/place_template(datum/map_template/random_room/template)
	var/datum/async_map_generator/map_place/generator = template.load(get_turf(src), centered = template.centerspawner)
	generator.on_completion(CALLBACK(src, PROC_REF(after_place)))

/obj/effect/spawner/room/proc/after_place(datum/async_map_generator/map_place/generator, turf/T, init_atmos, datum/parsed_map/parsed, finalize = TRUE, ...)
	// Scan through the room and remove any wall fixtures that were not placed correctly
	for (var/x in T.x to T.x + room_width - 1)
		for (var/y in T.y to T.y + room_height - 1)
			var/turf/current = locate(x, y, T.z)
			for (var/obj/placed_object in current)
				// Check if the object is a directional helper generated by MAPPING_DIRECTIONAL_HELPERS
				// We do this by finding "/directional" in its type path
				if (!findtext("[placed_object.type]", "/directional"))
					continue
				// Check to see if we correctly placed ourselves on a wall
				// Your file confirms REVERSE_DIR(dir) is available and calculates the direction back to the wall
				if (!isclosedturf(get_step(placed_object, REVERSE_DIR(placed_object.dir))))
					qdel(placed_object)


/obj/effect/spawner/room/special/tenxfive_terrestrial
	name = "10x5 terrestrial room"
	room_width = 10
	room_height = 5
	icon_state = "random_room_alternative"
	rooms = list(
	)

/obj/effect/spawner/room/special/tenxten_terrestrial
	name = "10x10 terrestrial room"
	room_width = 10
	room_height = 10
	icon_state = "random_room_alternative"
	rooms = list(
	)

/obj/effect/spawner/room/fivexfour
	name = "5x4 room spawner"
	room_width = 5
	room_height = 4

/obj/effect/spawner/room/fivexthree
	name = "5x3 room spawner"
	room_width = 5
	room_height = 3

/obj/effect/spawner/room/threexfive
	name = "3x5 room spawner"
	room_width = 3
	room_height = 5

/obj/effect/spawner/room/tenxten
	name = "10x10 room spawner"
	room_width = 10
	room_height = 10

/obj/effect/spawner/room/tenxfive
	name = "10x5 room spawner"
	room_width = 10
	room_height = 5

/obj/effect/spawner/room/threexthree
	name = "3x3 room spawner"
	room_width = 3
	room_height = 3

// Janitor
/obj/effect/spawner/room/janitor
	name = "Janitor Closet Room (9x10)"
	room_width = 9
	room_height = 10
	rooms = list(
		"janitor_rdm_standard",
		"janitor_rdm_plundered",
	)



/obj/effect/spawner/room/fland
	name = "Special Room (5x10)"
	icon_state = "random_room_alternative"
	room_width = 5
	room_height = 10


/*
/obj/effect/spawner/surface/echo
	name = "seasonal surface spawner"
	icon = 'icons/effects/landmarks_static.dmi'
	icon_state = "random_room_alternative"
	dir = NORTH

/obj/effect/spawner/surface/echo/Initialize(mapload)
	var/season = get_current_season()
	var/list/echo_season = list(
		"SUMMER" = "summer_surface",
		"WINTER" = "winter_surface",
		"SPRING" = "spring_surface",
		"AUTUMN" = "autumn_surface"
	)

	if (!(season in echo_season))
		message_admins("Echo surface spawner error: Unknown season '[season]'")
		return INITIALIZE_HINT_QDEL

	var/target_room_id = echo_season[season]
	var/datum/map_template/random_room/template = null

	for (var/datum/map_template/random_room/T in SSmapping.echo_surface_templates)
		if (T.room_id == target_room_id)
			template = T
			break

	if (!template)
		message_admins("Echo spawner: No surface map found for '[season]' ([target_room_id])")
		return INITIALIZE_HINT_QDEL

	message_admins("Echo spawner: Loading [template.name]. This may take a moment.")

	INVOKE_ASYNC(src, PROC_REF(place_template), template)

	return INITIALIZE_HINT_QDEL

/obj/effect/spawner/surface/echo/proc/place_template(datum/map_template/random_room/template)
	var/datum/async_map_generator/map_place/generator = template.load(get_turf(src), centered = template.centerspawner)
	generator.on_completion(CALLBACK(src, PROC_REF(after_place)))

/obj/effect/spawner/surface/echo/proc/after_place(datum/async_map_generator/map_place/generator, turf/T, init_atmos, datum/parsed_map/parsed, finalize = TRUE, ...)
	message_admins("Echo spawner: Surface placement complete.")

/proc/get_current_season()
	var/month = text2num(time2text(world.timeofday, "MM"))

	if (month in list(DECEMBER, JANUARY, FEBRUARY))
		return "WINTER"
	//if (month in list(MARCH, APRIL, MAY))
	//	return "SPRING"
	//if (month in list(SEPTEMBER, OCTOBER, NOVEMBER))
	//	return "AUTUMN"
	return "SUMMER" //"SUMMER" by default
*/
